【WIP】Calendar
ShotaTsuru/ruby-practices pull request #2
Opened 2021-06-25 04:14 UTC by ShotaTsuru

# What
カレンダープログラムの提出物

# why
提出物のレビュー依頼のため

2021-06-29 13:59 UTC, u1tnk requested changes

2021-06-29 13:59 UTC, u1tnk commented on 02.calendar/cal.rb
> +# opt.on('-m') {|v| v }
提出物にコメントアウトが残ってるのは良くないので気をつけましょう。

2021-06-29 13:59 UTC, u1tnk commented on 02.calendar/cal.rb
> +month = params["m"] unless params["m"] == nil
nilの場合は `params["m"].nil?` もありますが、この場合は `if params['m']` がシンプルで良いと思います。

2021-06-29 13:59 UTC, u1tnk commented on 02.calendar/cal.rb
> +  7.times do |i|
一時変数の x,yがあまり直感的じゃないのが気になりますね。
すぐ使うときの一文字変数はアリですが、この場合は一文字変数が3つあるので、どれがどれだろう？となってしまうので。
変数名をもう少しで良いので改善してみましょう。

2021-06-29 13:59 UTC, u1tnk commented on 02.calendar/cal.rb
> +week_case = ["  ","  ","  ","  ","  ","  ","  "]
` ["  ","  ","  ","  ","  ","  ","  "]` が何度も出てくるので定数化すると良いですね。
`week_case` に代入するときは cloneすればweek_caseの中身を書き替えても大丈夫です

2021-06-29 13:59 UTC, u1tnk commented on 02.calendar/cal.rb
> +  week_case = ["  ","  ","  ","  ","  ","  ","  "]
このweek_caseは ローカル変数では無く、最上位のweek_caseを参照していて分かりづらいですね。
上述の定数を使えばこのメソッドは不要になるとは思います。

2021-06-29 13:59 UTC, u1tnk commented on 02.calendar/cal.rb
> +first = set_week(First_week_day)
何度も繰り返すコードがでてきたらループにできないか考えてみましょう 💪

2021-06-29 13:59 UTC, u1tnk commented on 02.calendar/cal.rb
> +  return aset_array
rubyでreturnを書くのは途中で返すときだけで最後の行にあるときは書かないのが慣行となっています。

2021-06-29 13:59 UTC, u1tnk commented on 02.calendar/cal.rb
> +      num = Paint[num, :inverse] if num.to_i == Date.today.day && First_week_day.year == Date.today.year && First_week_day.month == Date.today.month
この行は if〜endの後に持っていけば一回で済むと思いますがどうでしょう？

2021-06-29 13:59 UTC, u1tnk commented on 02.calendar/cal.rb
> +def set_string_num(array)
これは今日だと反転する為の処理ですよね？関数名をもっと何をやっているのか分かりやすい名前にしてみましょう。
「今日だったら色を反転させる」
という意味が分かるように意識してみましょう。
コードを読む人が処理を読まなくても何が目的の処理か大体分かるのが良いメソッド名です。

2021-06-29 22:51 UTC, ShotaTsuru commented on 02.calendar/cal.rb
> +# opt.on('-m') {|v| v }
承知いたしました！

2021-06-29 22:53 UTC, ShotaTsuru commented on 02.calendar/cal.rb
> +month = params["m"] unless params["m"] == nil
真の判定がture以外を返す以外にもあることを忘れておりました！承知いたしました！

2021-06-29 23:23 UTC, ShotaTsuru commented on 02.calendar/cal.rb
> +week_case = ["  ","  ","  ","  ","  ","  ","  "]
定数化の意識がありませんでした！承知いたしました！

2021-06-29 23:23 UTC, ShotaTsuru commented on 02.calendar/cal.rb
> +  return aset_array
チェリー本でそのことを知るまで完全に癖になってました！承知いたしました！

2021-06-30 01:28 UTC, ShotaTsuru commented
修正箇所が多くなり申し訳ありません🙇‍♂️🙇‍♂️
お手数ですがご確認お願いいたします！！

2021-06-30 05:28 UTC, u1tnk requested changes

2021-06-30 05:28 UTC, u1tnk commented on 02.calendar/cal.rb
> +    wday_num = week_day.wday + i
numというのは数字を表すしか情報が無く、付ける必要が無いと思います。
dateの方はついていませんし。

2021-06-30 05:28 UTC, u1tnk commented on 02.calendar/cal.rb
> +  array.each do |x|
書き替えなくても良いですが、mapを使うと以下のようにかけるので覚えておきましょう。rubyっぽい感じです 😎 

```
def two_digit_conversion_and_color_inversion(array)
  array.map do |x|
    num = ''
    if x.to_s.length != 2
      num = " #{x.to_s}"
    else
      num = x.to_s
    end
    num = Paint[num, :inverse] if num.to_i == Date.today.day && FIRST_WEEK_DAY.year == Date.today.year && FIRST_WEEK_DAY.month == Date.today.month
    num
  end
end
```

2021-06-30 05:28 UTC, u1tnk commented on 02.calendar/cal.rb
> +def two_digit_conversion_and_color_inversion(array)
だいぶ良くなりました！
ただ、ちょっと長いので、メソッド名長い=メソッドが複雑になってるのでは？と考えましょう。
andの前後でメソッドを分けるとシンプルになるのではと思います。

2021-06-30 05:28 UTC, u1tnk commented on 02.calendar/cal.rb
> +  week_case = EMPTY_ARRAY7.clone
week_caseというのはどういう意図の変数名なのでしょうか？ case = ケースで容れもの？ 
ちなみにプログラミングのコンテキストだと caseは `camelCase/snake_case`(区切り方) `uppper case/lower case`(大文字小文字)、 case 〜when (場合)を連想してしまいます。

2021-06-30 05:28 UTC, u1tnk commented on 02.calendar/cal.rb
> +all_week_array = [aset_week(FIRST_WEEK_DAY)]
rubyというかrails界隈では複数形で配列をあらわす事が多いので、 all_weeks で良いかと思います。

2021-06-30 05:28 UTC, u1tnk commented on 02.calendar/cal.rb
> +EMPTY_ARRAY7 = ['  ','  ','  ','  ','  ','  ','  ']
EMPTYは良いのですが、 ARRAY7だと何が入ってるか推測が難しいですね。
これなら EMPTY_WEEK ぐらいでしょうか。

2021-06-30 05:33 UTC, ShotaTsuru commented on 02.calendar/cal.rb
> +def two_digit_conversion_and_color_inversion(array)
なるほど納得です！分割いたします！

2021-06-30 05:42 UTC, ShotaTsuru commented on 02.calendar/cal.rb
> +  week_case = EMPTY_ARRAY7.clone
確かに！！caseは入れ物の意図で使ったのですが、case~whenを連想させてしまうと不適切ですね😅
他の変数名にいたします！

2021-06-30 06:57 UTC, ShotaTsuru commented on 02.calendar/cal.rb
> +all_week_array = [aset_week(FIRST_WEEK_DAY)]
プラクティスで書かれていることをしっかり実践できておらず申し訳ありません！
修正いたしました！

2021-06-30 06:58 UTC, ShotaTsuru commented on 02.calendar/cal.rb
> +EMPTY_ARRAY7 = ['  ','  ','  ','  ','  ','  ','  ']
ありがとうございます！🙇‍♂️🙇‍♂️EMPTY_WEEKでの命名使わせていただきます！！

2021-06-30 07:00 UTC, ShotaTsuru commented on 02.calendar/cal.rb
> +    wday_num = week_day.wday + i
承知いたしました！結構numを使いがちなので気をつけます！

2021-06-30 07:22 UTC, ShotaTsuru commented on 02.calendar/cal.rb
> +  array.each do |x|
injectの配列版をなかなか思い出せなかったのでご教授頂きありがとうございます！！mapで実装いたします!

2021-06-30 07:27 UTC, ShotaTsuru commented
とても細やかなフィードバックありがとうございます！
修正完了いたしました！
お手数ですがご確認お願いいたします！🙇‍♂️🙇‍♂️🙇‍♂️

2021-06-30 11:54 UTC, u1tnk approved these changes

2021-06-30 12:20 UTC, merged